[build]

	# Deploy from demo
	base = "demo/"
	publish = 'dist'

	# Always re-build on demo sites
	command = 'CI= yarn generate --force-build'

	# Trigger redeploys on any change
	ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../"
