[dev]
   command = "yarn dev"

[build]
  command = 'CI= yarn generate --force-build'
  publish = 'dist'

  # Trigger redeploys on any change
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../"
